[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "altair<5.0.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
    "reportlab>=4.4.9",
    "streamlit>=1.19.0",
]
